# github_api_helper.py
# file containing helper functions to interact with GitHub API.

from __future__ import annotations

from pathlib import Path
from typing import Any
from tqdm import tqdm

import time
import os
import httpx
import pandas as pd

from src.russian_classifier import build_russian_candidates
from src.artifacts import read_csv_if_exists, save_csv

GITHUB_API = "https://api.github.com"


# Russian words we search for
DEFAULT_SEARCH_TERMS = [
  "и", "в", "не", "на", "что", "это", "как", "так",
  "если", "можно", "нужно", "спасибо", "ошибка",
  "проблема", "работает", "исправить",
]

# bot/autogenerated pruning helpers
AUTOGENERATED_PATTERNS = [
  "auto-generated comment", "automated comment", "this is an auto-generated",
  "generated by", "generated with", "generated using", "ai-generated", "created by ai",
  "written by ai",

  "github-actions", "github actions", "coderabbit", "code rabbit", "copilot",
  "github copilot", "copilot review", "copilot summary", "copilot generated", "dependabot",
  "renovate bot", "stale bot", "prettier bot",

  "walkthrough_start", "walkthrough_end", "pre_merge_checks", "internal state start",
  "internal state end", "finishing_touch_checkbox", "tips_start", "tips_end",

  "rsi diff bot", "diff updated after", "pre-merge checks failed", "suggested reviewers",
  "estimated code review effort", "prompt for ai agents",
  "verify each finding against the current code", "committable suggestion",
]

# amend headers in HTTP request to GitHub API.
# it is advised to use GitHub API token to avoid extra request cooldown time
# for unauthorized users.
def github_headers() -> dict[str, str]:
  token = os.environ.get("GITHUB_TOKEN")

  headers = {
    "Accept": "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28",
    "User-Agent": "bep-varapai-russian-dataset-fetcher",
  }

  if token:
    headers["Authorization"] = f"Bearer {token}"

  return headers


# get a guaranteed response from GitHub API and sleep if it hits API rate limit.
def gh_get(
  client: httpx.Client,
  url: str,
  params: dict[str, Any] | None = None,
) -> Any:
  while True:
    response = client.get(url, params=params)

    if response.status_code in {403, 429}:
      reset = response.headers.get("x-ratelimit-reset")

      if reset is not None:
        wait_seconds = max(0, int(reset) - int(time.time())) + 5
      else:
        wait_seconds = 60

      print(f"\nGitHub rate/API limit. Sleeping {wait_seconds}s.", flush=True)
      time.sleep(wait_seconds)
      continue

    response.raise_for_status()
    return response.json()


# query GitHub API URL page-by-page
def gh_get_paginated(
  client: httpx.Client,
  url: str,
  max_pages: int,
  params: dict[str, Any] | None = None,
) -> list[dict[str, Any]]:
  rows: list[dict[str, Any]] = []

  for page in range(1, max_pages + 1):
    page_params = dict(params or {})
    page_params["per_page"] = 100
    page_params["page"] = page

    data = gh_get(client, url, params=page_params)

    if not isinstance(data, list) or not data:
      break

    rows.extend(data)

    # when a 100-element page is shorter than 100, we have hit the end.
    if len(data) < 100:
      break

  return rows


# exhaustive search through GitHub PRs by a given term
def search_prs_for_term(
  client: httpx.Client,
  term: str,
  max_pages: int,
) -> list[dict[str, Any]]:
  rows: list[dict[str, Any]] = []
  query = f'is:pr is:public comments:>0 "{term}"'

  for page in range(1, max_pages + 1):
    data = gh_get(
      client,
      f"{GITHUB_API}/search/issues",
      params={
        "q": query,
        "sort": "updated",
        "order": "desc",
        "per_page": 100,
        "page": page,
      },
    )

    items = data.get("items", [])

    for item in items:
      if "pull_request" not in item:
        continue

      rows.append({
        "pr_url": item.get("html_url"),
        "pr_api_url": item.get("url"),
        "repository_url": item.get("repository_url"),
        "pr_number": item.get("number"),
        "pr_title": item.get("title"),
        "retrieval_term": term,
        "retrieval_query": query,
        "updated_at": item.get("updated_at"),
        "created_at": item.get("created_at"),
      })

    if len(items) < 100:
      break

  return rows


# get repository name from its URL
def repo_from_repository_url(repository_url: str) -> str:
  prefix = f"{GITHUB_API}/repos/"

  if not repository_url.startswith(prefix):
    raise ValueError(f"Unexpected repository_url: {repository_url}")

  return repository_url.removeprefix(prefix)


# query all PRs containing given keywords
def collect_prs(
  client: httpx.Client,
  search_terms: list[str],
  max_pages: int,
) -> pd.DataFrame:
  rows: list[dict[str, Any]] = []

  for term in tqdm(search_terms, desc="Searching PRs"):
    rows.extend(search_prs_for_term(client, term, max_pages=max_pages))
    time.sleep(0.2)

  df = pd.DataFrame(rows)

  if df.empty:
    return df

  df["repo_full_name"] = df["repository_url"].apply(repo_from_repository_url)

  df = df.drop_duplicates(
    subset=["repo_full_name", "pr_number"],
    keep="first",
  ).reset_index(drop=True)

  return df


# fetch given amount of pages of issues, reviews and review comments
def fetch_pr_discussion(
  client: httpx.Client,
  repo_full_name: str,
  pr_number: int,
  pr_url: str,
  max_comment_pages: int,
) -> list[dict[str, Any]]:
  owner, repo = repo_full_name.split("/", maxsplit=1)

  issue_comments = gh_get_paginated(
    client,
    f"{GITHUB_API}/repos/{owner}/{repo}/issues/{pr_number}/comments",
    max_pages=max_comment_pages,
  )

  review_comments = gh_get_paginated(
    client,
    f"{GITHUB_API}/repos/{owner}/{repo}/pulls/{pr_number}/comments",
    max_pages=max_comment_pages,
  )

  reviews = gh_get_paginated(
    client,
    f"{GITHUB_API}/repos/{owner}/{repo}/pulls/{pr_number}/reviews",
    max_pages=max_comment_pages,
  )

  rows: list[dict[str, Any]] = []

  for comment in issue_comments:
    rows.append({
      "repo_full_name": repo_full_name,
      "pr_number": pr_number,
      "pr_url": pr_url,
      "comment_source": "issue_comment",
      "comment_id": comment.get("id"),
      "comment_url": comment.get("html_url"),
      "user_login": (comment.get("user") or {}).get("login"),
      "created_at": comment.get("created_at"),
      "updated_at": comment.get("updated_at"),
      "body": comment.get("body"),
      "path": None,
      "commit_id": None,
    })

  for comment in review_comments:
    rows.append({
      "repo_full_name": repo_full_name,
      "pr_number": pr_number,
      "pr_url": pr_url,
      "comment_source": "review_comment",
      "comment_id": comment.get("id"),
      "comment_url": comment.get("html_url"),
      "user_login": (comment.get("user") or {}).get("login"),
      "created_at": comment.get("created_at"),
      "updated_at": comment.get("updated_at"),
      "body": comment.get("body"),
      "path": comment.get("path"),
      "commit_id": comment.get("commit_id"),
    })

  for review in reviews:
    body = review.get("body")

    if body is None or not str(body).strip():
      continue

    rows.append({
      "repo_full_name": repo_full_name,
      "pr_number": pr_number,
      "pr_url": pr_url,
      "comment_source": "review_body",
      "comment_id": review.get("id"),
      "comment_url": review.get("html_url"),
      "user_login": (review.get("user") or {}).get("login"),
      "created_at": review.get("submitted_at"),
      "updated_at": review.get("submitted_at"),
      "body": body,
      "path": None,
      "commit_id": review.get("commit_id"),
    })

  return rows


# ensure each comment is unique and valid
def normalize_comments(df: pd.DataFrame) -> pd.DataFrame:
  if df.empty:
    return df

  if "comment_id" not in df.columns:
    return df

  df = df.dropna(subset=["comment_id"]).copy()

  df = df.drop_duplicates(
    subset=["comment_source", "comment_id"],
    keep="first",
  ).reset_index(drop=True)

  return df


# return a set of unique PR identifiers to which the comments from given list belong
def fetched_pr_keys(comments: pd.DataFrame) -> set[tuple[str, int]]:
  if comments.empty:
    return set()

  required = {"repo_full_name", "pr_number"}

  if not required <= set(comments.columns):
    return set()

  keys: set[tuple[str, int]] = set()

  # since keys is a set, repo identifiers are not duplicated
  for row in comments[["repo_full_name", "pr_number"]].dropna().itertuples(index=False):
    keys.add((str(row.repo_full_name), int(row.pr_number)))

  return keys

# from a given set of comments, estimate how many would be eligible
def estimate_candidate_count(comments: pd.DataFrame) -> int:
  if comments.empty:
    return 0

  candidates = build_russian_candidates(
    comments,
    text_col="body",
    min_chars=8,
    max_chars=500,
    min_cyrillic_chars=4,
    min_cyrillic_ratio=0.3,
  )

  return len(candidates)


# test user name against known AI bot names
def is_bot_user(user_login: object) -> bool:
  value = "" if pd.isna(user_login) else str(user_login).lower()

  if value.endswith("[bot]"):
    return True

  bot_names = {
    "github-actions",
    "github-actions[bot]",
    "coderabbitai[bot]",
    "dependabot[bot]",
    "renovate[bot]",
    "copilot-pull-request-reviewer[bot]",
    "copilot[bot]",
  }

  return value in bot_names


# test comment body against common autogenerated patterns
def is_autogenerated_body(body: object) -> bool:
  value = "" if pd.isna(body) else str(body).lower()

  return any(pattern in value for pattern in AUTOGENERATED_PATTERNS)


# use is_bot_user and is_autogenerated_body to prune comments
def prune_comments(df: pd.DataFrame) -> pd.DataFrame:
  if df.empty:
    return df

  result = df.copy()

  if "user_login" in result.columns:
    result = result[~result["user_login"].apply(is_bot_user)].copy()

  if "body" in result.columns:
    result = result[~result["body"].apply(is_autogenerated_body)].copy()

  return result.reset_index(drop=True)


# main function to fetch PR review comments
def collect_comments(
  client: httpx.Client,
  prs: pd.DataFrame,
  max_comment_pages: int,
  checkpoint_path: Path,
  checkpoint_every: int,
  target_candidates: int,
  max_comments_per_pr: int,
  min_chars: int,
  max_chars: int,
) -> pd.DataFrame:

  # try access cached comments 
  cached = read_csv_if_exists(checkpoint_path)
  if cached is not None:
    rows_df = normalize_comments(cached)

    # from fetched comments, determine unique PRs
    done_keys = fetched_pr_keys(rows_df)
    print(
      f"Resuming comments from checkpoint: "
      f"{len(rows_df)} comments, {len(done_keys)} PRs already used"
    )
  # if not cached, start with empty rows_df and done_keys
  else:
    rows_df = pd.DataFrame()
    done_keys = set()

  # if PRs df (input argument) is empty, there is no work to be done
  if prs.empty:
    return rows_df

  current_rows = rows_df.to_dict("records")
  current_count = len(rows_df)

  # populate remaining_prs with all PRs not in done_keys
  remaining_prs = []
  for pr in prs.itertuples(index=False):
    key = (str(pr.repo_full_name), int(pr.pr_number))

    if key not in done_keys:
      remaining_prs.append(pr)


  print(f"Remaining PRs to inspect: {len(remaining_prs)}/{len(prs)}")
  print(f"Current accepted candidate comments: {current_count}/{target_candidates}")

  # ensure the progress bar reflects only the work needed to reach target_candidates
  remaining_needed = max(0, target_candidates - current_count)
  loop_total = min(len(remaining_prs), remaining_needed) if remaining_needed > 0 else 0

  # render the progress bar
  for count, pr in enumerate(
    tqdm(remaining_prs, total=loop_total, desc="Fetching PR discussions"),
    start=1,
  ):
    if current_count >= target_candidates:
      print("Target candidate count reached. Stopping.")
      break

    try:
      pr_rows = fetch_pr_discussion(
        client=client,
        repo_full_name=str(pr.repo_full_name),
        pr_number=int(pr.pr_number),
        pr_url=str(pr.pr_url),
        max_comment_pages=max_comment_pages,
      )
    except httpx.HTTPStatusError as exc:
      print(f"\nSkipping {pr.repo_full_name}#{pr.pr_number}: {exc}")
      continue
    except ValueError as exc:
      print(f"\nSkipping malformed PR row: {exc}")
      continue

    # deduplicate comments
    pr_df = normalize_comments(pd.DataFrame(pr_rows))
    # prune AI-generated comments
    pr_df = prune_comments(pr_df)

    # if no messages are left, try next PR
    if pr_df.empty:
      continue

    # only leave out messages in Russian that could be labeled
    pr_candidates = build_russian_candidates(
      pr_df,
      text_col="body",
      min_chars=min_chars,
      max_chars=max_chars,
      min_cyrillic_chars=4,
      min_cyrillic_ratio=0.3,
    )

    # if no candidates found, move on to the next PR
    if pr_candidates.empty:
      continue

    # limit the amount of messages to max_comments_per_pr
    pr_candidates = pr_candidates.head(max_comments_per_pr)

    # make sure the amount of messages added will not overflow target_candidates
    remaining_slots = target_candidates - current_count
    pr_candidates = pr_candidates.head(remaining_slots)

    # append mined messages
    current_rows.extend(pr_candidates.to_dict("records"))
    current_count += len(pr_candidates)

    # save a checkpoint for a possible re-run
    if count % checkpoint_every == 0:
      checkpoint_df = normalize_comments(pd.DataFrame(current_rows))
      save_csv(checkpoint_df, checkpoint_path)
      print(f"Accepted candidate comments: {current_count}/{target_candidates}")

    # brief pause to reduce GitHub API rate-limit risk when iterating over
    # many PRs/comments; 150ms was chosen as a small throttle between requests.
    time.sleep(0.15)

  # finalize selection
  final_df = normalize_comments(pd.DataFrame(current_rows))
  save_csv(final_df, checkpoint_path)

  return final_df


# read newline-separated terms
def read_terms(path: Path | None) -> list[str]:
  if path is None:
    return DEFAULT_SEARCH_TERMS

  terms: list[str] = []

  for line in path.read_text(encoding="utf-8").splitlines():
    line = line.strip()

    if not line or line.startswith("#"):
      continue

    terms.append(line)

  return terms

